### ISSUE TITLE
The old version of the code with an error is being downloaded from the website link.

### ISSUE THREAD

**Issue by krdprog** [edgecase/ruby_koans#39]
Error on the website https://www.rubykoans.com/

The old version of the code with an error is being downloaded from the website link. In top-right button: https://github.com/edgecase/ruby_koans/blob/master/download/rubykoans.zip?raw=true

The downloaded archive contains old code and it has an error when working with Ruby 3.2.

```ruby
koans/neo.rb:221:in `add_progress': undefined method `exists?' for File:Class (NoMethodError)

      exists = File.exists?(PROGRESS_FILE_NAME)
```
Fix, please for us.

**Comment by zhabinka** [comment]
This is first task! :)

**Comment by tonywok** [comment]
Updated! Sorry for the delay 😅
